//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bills")]
pub struct Model {
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event_id: String,
    pub from_addr: Option<String>,
    pub to_addr: Option<String>,
    pub event_type: String,
    pub direction: i8,
    #[sea_orm(column_type = "Decimal(Some((22, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((22, 2)))")]
    pub current_balance: Decimal,
    pub ext_desc: Option<String>,
    pub info: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
