//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::bill::Entity as Bills;
pub use super::transaction_events::Entity as TransactionEvents;
pub use super::wallets::Entity as Wallets;
